app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topics:
      email: email
  transport:
    type: ${TRANSPORT_TYPE}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}
  redis:
    prefix: ${REDIS_PREFIX}
  jwt:
    secret: ${JWT_SECRET}
  cloud:
    key-id: ${OBJECT_STORAGE_KEY_ID}
    key-secret: ${OBJECT_STORAGE_KEY_SECRET}
    url: ${OBJECT_STORAGE_URL}
    tenant-id: ${OBJECT_STORAGE_TENANT_ID}
    bucket: ${OBJECT_STORAGE_BUCKET}


server:
  port: ${USER_PORT}

spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: error
    web: warn

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui